spack:
  specs:
  - openmpi@4.1.4 fabrics=ofi +legacylaunchers
  - libfabric@1.19.0 fabrics=efa,tcp,udp,sockets,verbs,shm,mrail,rxd,rxm
  - flux-sched
  - flux-core
  - pmix@4.2.2
  - flux-pmix@0.4.0
  - amg2023 +mpi +openmp
  - hypre +int64 +openmp
  concretizer:
    unify: true
  config:
    install_tree:
      root: /opt/software
  view: /opt/view
  packages:
    cmake:
      externals:
      - spec: cmake@3.26.5
        prefix: /usr
    openssh:
      externals:
      - spec: openssh@8.0p1
        prefix: /usr
  compilers:
  - compiler:
      spec: gcc@=8.5.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: rocky8
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
