spack:
  specs:
  - amg2023 %gcc@11.4.0 +mpi +openmp ^cmake@3.22.1 ^hpcx-mpi@2.19%gcc@11.4.0
  - hypre %gcc@11.4.0 +mpi +openmp +int64 ^hpcx-mpi@2.19%gcc@11.4.0 
  packages:
    hpcx-mpi:
      externals:
      - spec: hpcx-mpi@2.19
        modules:
        - mpi/hpcx
        prefix: /opt/hpcx-v2.19-gcc-mlnx_ofed-ubuntu22.04-cuda12-x86_64/ompi
    cmake:
      externals:
      - spec: cmake@3.22.1
        prefix: /usr
      buildable: false
  compilers:
  - compiler:
      spec: gcc@=11.4.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags:
        cflags: -O3 -Ofast -fopenmp 
        cxxflags: -O3 -Ofast -fopenmp 
        fflags: -O3 -Ofast -fopenmp 
      modules: []
      operating_system: rocky8
      environment: {}
      extra_rpaths: []
  config:
    install_tree:
      root: /opt/view
